---
version: 2
models:
- name: "orders"
  columns:
  - name: "id"
    dataType:
      type: "Integer"
  - name: "order_id"
    dataType:
      type: "String"
  - name: "amount"
    dataType:
      type: "Integer"
  - name: "payment_method"
    dataType:
      type: "String"
- name: "use_model"
  columns:
  - name: "id"
    tests:
    - unique:
        config:
          store_failures: true
          fail_calc: "count(*)"
          severity: "warn"
          where: "id < 2000"
          limit: 10
    - relationships:
        config:
          where: "id != 1"
        to: "ref('raw_ints')"
        field: "int"
    - github_dbt_base.min_value_test:
        config: {}
        threshold: "\"-1\""
    - max_value_test:
        config: {}
        threshold: "\"10000\""
    dataType:
      type: "Integer"
