---
version: 2
models:
- name: "use_model"
  columns:
  - name: "id"
    tests:
    - unique:
        config: {}
        column_name: "id"
    - max_value_test:
        config: {}
        column_name: "\"id\""
        threshold: 5000
    dataType:
      type: "Integer"
  tests:
  - not_null:
      config: {}
      column_name: "id"
