---
version: 2
models:
- name: "use_model"
  columns:
  - name: "id"
    tests:
    - unique:
        column_name: "id"
    - not_null:
        column_name: "id"
    - custom_unique:
        column_name: "id"
        config:
          severity: "error"
          limit: 10
          store_failures: true
    - relationships:
        field: "int"
        column_name: "id"
        to: "raw_ints"
    dataType:
      type: "Integer"
  tests: []
- name: "orders"
  columns: []
  tests:
  - not_null:
      column_name: "id"
      config:
        severity: "warn"
  - accepted_values:
      values:
      - "debit_card"
      - "cc_card"
      - "wire"
      column_name: "payment_method"
      config:
        store_failures: true
        warn_if: " != 0"
        error_if: " != 0"
        severity: "warn"
        where: "id > 2"
        limit: 10
  - min_value_test:
      config: {}
      column_name: "id"
      threshold: "-1"
