---
version: 2
models:
- name: "orders"
  columns:
  - name: "USER_ID"
    dataType:
      type: "Integer"
  - name: "amount"
    dataType:
      type: "Integer"
  - name: "payment_method"
    dataType:
      type: "String"
  - name: "ID"
    tests:
    - unique:
        config:
          store_failures: true
          fail_calc: "count(*)"
          where: "ID != 1"
          error_if: " BETWEEN 1 AND 10000"
          severity: "warn"
          limit: 10
        column_name: "ID"
    dataType:
      type: "Integer"
  - name: "order_date"
    dataType:
      type: "Date"
  - name: "status"
    tests:
    - accepted_values:
        values:
        - "placed"
        - "shipped"
        - "completed"
        - "returned"
        - "return_pending"
    dataType:
      type: "String"
